### ISSUE TITLE
Could you explain how to use commands for this script?

### ISSUE THREAD

**Issue by morosakubek** [phyyyl/srt#1]
Hi,
Could you explain how to use commands for this script?

best,
M.

**Comment by 1cedsoda** [comment]
Hello,
I drafted a new release:[ v1.1](https://github.com/phyyyl/srt/releases/tag/1.1)
I debugged the code, added this[ wiki page](https://github.com/phyyyl/srt/wiki/How-to-use) and instructions to the command line when you run the script directly.
